t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: custom
  customPackage: com.epion_t3.custom
  summary:
    - lang: ja_JP
      contents: "独自にカスタムした機能を提供します。"
  description:
    - lang: ja_JP
      contents: "独自にカスタムした機能を提供します。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # ExcelBindVariables
  ##########################
  - id: ExcelBindVariables
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "Excelファイルに対して変数のバインドを行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: Excel「${target}」に対して変数をバインドします。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "Excelの全てのシートに対して変数をバインドします。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "変数の参照記法「${スコープ.変数名}」が記載してあるセルの値を置換します。（部分置換を行えます）"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "セルの型が「文字列」である場合にのみ置換します。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "置換後のExcelファイルは、エビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「BindVariables_ + 元ファイル名」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「ExcelBindVariables」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするExcelの相対パス"
#####################################
# メッセージ定義
#####################################
messages:
