name: build_and_publish_lib
on:
  push:
    branches:
      - master
jobs:
  first_job:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Start
        uses: actions/checkout@master
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build
      - name: Publish
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        run: ./gradlew bintrayUpload -PbintrayUser=${BINTRAY_USER} -PbintrayApiKey=${BINTRAY_API_KEY}